version: '3.4'

services:
    api:
        environment:
            IIIF_URI: http://${LOCAL_IP}:8081/iiif/2
    journal:
        environment:
            SYMFONY__API_URL_PUBLIC: http://${LOCAL_IP}:8081
