version: '3.4'

services:
    api:
        build:
            context: api
        environment:
            IIIF_URI: ${IIIF_URI:-http://localhost:8081/iiif/2}
    journal:
        build:
            context: journal
            args:
                app_env: prod
                api_url: http://api:8080
                api_url_public: ${API_URL_PUBLIC:-http://localhost:8081}
                api_key: public
        volumes:
            - public-journal:/app/web/
        depends_on:
            - api
    iiif:
        image: mitlibraries/cantaloupe:latest
        environment:
            SOURCE_STATIC: FilesystemSource
            FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: /imageroot/
            FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_SUFFIX: ''
            PROCESSOR_FALLBACK: Java2dProcessor
            CACHE_SERVER_DERIVATIVE: FilesystemCache
            OVERLAYS_STRATEGY: BasicStrategy
            FILESYSTEMCACHE_PATHNAME: /cache
        volumes:
            - ./assets/files:/imageroot:ro
        ports:
            - 8081:8182
    web:
        image: nginx:1.15.5-alpine
        volumes:
            - ./journal/.docker/nginx.conf:/etc/nginx/conf.d/journal.conf
            - ./assets/.docker/nginx.conf:/etc/nginx/conf.d/assets.conf
            - public-journal:/app/journal/:ro
            - ./assets/files:/app/assets:ro
        ports:
            - 8080:8080
            - 8082:8082
        depends_on:
            - journal

volumes:
    public-journal:
