imports:
  - resource: config.yml

parameters:
    api_connect_timeout: 2
    api_timeout: 5
    api_connect_timeout_slow: 3
    api_timeout_slow: 10
    mustache_stat_props: ~

framework:
    session:
        cookie_secure: true
    trusted_hosts: '%trusted_hosts%'

monolog:
    handlers:
        console:
            type: console
        main:
            action_level: error
            handler: composite
            type: fingers_crossed
            excluded_404s:
                - ^/
        composite:
            type: whatfailuregroup
            members:
                - text
                - json
                - newrelic
        text:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.txt.log'
            level: debug
            formatter: monolog.formatter.line
        json:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.json.log'
            level: debug
            formatter: monolog.formatter.json
        newrelic:
            type: newrelic
            level: error
