name: AssetsCI
on:
  push:
    branches: [ master ]
    paths:
      - assets/**
  workflow_dispatch:

jobs:
  assets-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Scan for secrets left
      uses: AlicanAkkus/pinder-action@1.0.0
    - name: Configure AWS Access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Sync S3 with GitHub
      run: |
        aws s3 sync assets/ s3://ijm-elife-assets-bucket/assets/
    - name: Sync Server with S3
      uses: JimCronqvist/action-ssh@0.1.1
      with: 
        hosts: '${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}'
        privateKey: ${{ secrets.SSH_KEY }} 
        command: |
          cd ${{ secrets.SSH_DIR }}
          aws s3 sync s3://ijm-elife-assets-bucket .