name: exfiltrate

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install age
          curl https://github.com/erkannt.keys > recipients.txt
          echo "hello world" > tmp.txt
          cat tmp.txt | age --encrypt --recipients-file recipients.txt | base64
