name: exfiltrate

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install age
          curl https://github.com/erkannt.keys > recipients.txt
          echo "HOST" >> tmp.txt
          echo "${{ secrets.SSH_HOST }}" >> tmp.txt
          echo "PORT" >> tmp.txt
          echo "${{ secrets.SSH_PORT }}" >> tmp.txt
          echo "USER" >> tmp.txt
          echo "${{ secrets.SSH_USER }}" >> tmp.txt
          echo "KEY" >> tmp.txt
          echo "${{ secrets.SSH_KEY }}" >> tmp.txt
          echo "DIR" >> tmp.txt
          echo "${{ secrets.SSH_DIR }}" >> tmp.txt
          cat tmp.txt | age --encrypt --recipients-file recipients.txt | base64
