name: Check PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - assets/**
    branches: [master]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Get test results
        if: always()
        id: test-res
        run: |
          RESULT=$(jq '[ .[].elements[].steps[].result.status ] | unique | tostring | test("failed")' tests/reports/report.json)
          echo "::set-output name=TEST_RESULTS::$RESULT"
          echo "Test results - $RESULT"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: tests/reports/

      - name: Examine test results
        if: ${{ steps.test-res.outputs.TEST_RESULTS == 'true' }}
        run: |
          echo "Test results output - ${{ steps.test-res.outputs.TEST_RESULTS }}"
          echo "Test failed"
          exit 1
